In [138]:
import pandas as pd

In [139]:
data=pd.read_excel("d:\pg project responses/res 1.xlsx")
data

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\44199919.py:1: SyntaxWarning: invalid escape sequence '\p'
  data=pd.read_excel("d:\pg project responses/res 1.xlsx")

,Name,Gender,Age,Employment Status,Education Qualification,District,Area of Residence,which type of Vehicle do you have?,Do you have an Electric Vehicle?,1.1 current awareness,...,4.5 cost consideration,5.1 consumer preference,5.2 consumer preference,5.3 consmer preference,5.4 consumer preference,5.5 consumer preference,6.1 evm consideration,6.2 evm consideration,6.3 evm consideration,6.4 evm consideration
0,Anish Glorisha,Female,18 - 27,Student,Post Graduate,Coimbatore,Urban,Petrol,No,fair,...,High,familiar,Attracted,Very satisfied,Somewhat considered,Good,Similar to others,Neutral,Reduce,neutral
1,Hari,Male,18 - 27,Student,Post Graduate,coimbatore,Rural,Diesel,Yes,good,...,Low,Very unfamiliar,Highly not attracted,moderately satisfied,Somewhat considered,Average,Highly polluting,Useless,Didn't reduce,support
2,CHINNAPPANDI J,Male,18 - 27,Student,Post Graduate,coimbatore,Rural,Petrol,Yes,poor,...,Very low,familiar,Not attracted,Very satisfied,Somewhat considered,Fair,Not polluting,Usefull,Definitely reduce,definitely support
3,P. Manikandan,Male,18 - 27,Student,Post Graduate,Viruthunagar,Urban,Diesel,Yes,very poor,...,Neutral,Somewhat familiar,Highly not attracted,moderately satisfied,Not considered,Fair,Similar to others,Usefull,Reduce,neutral
4,Divyasri,Female,18 - 27,Student,Post Graduate,Dharmapuri,Urban,Petrol,No,good,...,High,familiar,Not attracted,Slightly satisfied,Somewhat considered,Fair,slightly polluting,Neutral,Reduce,neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,Karuppaiya,Male,28 - 43,Employed,Diploma,Tiruppur,Urban,Petrol,No,good,...,Very low,familiar,Somewhat attracted,moderately satisfied,Somewhat considered,Poor,Highly not polluting,Very usefull,Definitely reduce,definitely support
197,Vishal,Male,18 - 27,Employed,Under Graduate,Tiruppur,Urban,Electric batteries,Yes,good,...,Low,Very familiar,Highly attracted,moderately satisfied,Considered,Poor,Highly not polluting,Very usefull,Definitely reduce,definitely support
198,Nivedha,Female,18 - 27,Employed,Post Graduate,Tiruppur,Urban,Petrol,No,good,...,Very low,familiar,Attracted,moderately satisfied,Somewhat considered,Poor,Highly not polluting,Very usefull,Definitely reduce,definitely support
199,Xavier,Male,18 - 27,Employed,Under Graduate,Tiruppur,Urban,Petrol,No,poor,...,Very low,Very familiar,Attracted,moderately satisfied,Somewhat considered,Poor,Highly not polluting,Very usefull,Definitely reduce,definitely support
200,S.Gangaiarasan,Male,44 - 59,Employed,Post Graduate,Pudukkottai,Rural,Petrol,No,poor,...,Very low,Unfamiliiar,Not attracted,Not at all satisfied,Not considered,Poor,Not polluting,Usefull,Reduce,neutral

In [140]:
data.dtypes

Name                                  object
Gender                                object
Age                                   object
Employment Status                     object
Education Qualification               object
District                              object
Area of Residence                     object
which type of Vehicle do you have?    object
Do you have an Electric Vehicle?      object
1.1 current awareness                 object
1.2 current awareness                 object
1.3 current awareness                 object
1.4 current awareness                 object
2.1 user satisfaction                 object
2.2 user satisfaction                 object
2.3 user satisfaction                 object
2.4 user satisfaction                 object
2.5 user satisfaction                 object
3.1 charging facilities               object
3.2 charging facilities               object
3.3 charging facilities               object
3.4 charging facilities               object
4.1 cost consideration                object
4.2 cost consideration                object
4.3 cost consideration                object
4.4 cost consideration                object
4.5 cost consideration                object
5.1 consumer preference               object
5.2 consumer preference               object
5.3 consmer preference                object
5.4 consumer preference               object
5.5 consumer preference               object
6.1 evm consideration                 object
6.2 evm consideration                 object
6.3 evm consideration                 object
6.4 evm consideration                 object
dtype: object

In [141]:
data.columns

Index(['Name', 'Gender', 'Age', 'Employment Status',
       'Education Qualification ', 'District', 'Area of Residence',
       'which type of Vehicle do you have?',
       'Do you have an Electric Vehicle?', '1.1 current awareness',
       '1.2 current awareness', '1.3 current awareness',
       '1.4 current awareness', '2.1 user satisfaction',
       '2.2 user satisfaction', '2.3 user satisfaction',
       '2.4 user satisfaction', '2.5 user satisfaction',
       '3.1 charging facilities', '3.2 charging facilities',
       '3.3 charging facilities', '3.4 charging facilities',
       '4.1 cost consideration', '4.2 cost consideration',
       '4.3 cost consideration', '4.4 cost consideration',
       '4.5 cost consideration', '5.1 consumer preference',
       '5.2 consumer preference', '5.3 consmer preference',
       '5.4 consumer preference', '5.5 consumer preference',
       '6.1 evm consideration', '6.2 evm consideration',
       '6.3 evm consideration', '6.4 evm consideration'],
      dtype='object')

In [142]:
data['1.4 current awareness'].value_counts()

1.4 current awareness
Agree                108
Neutral               51
Strongly agree        27
Disagree               9
strongly disagree      6
Name: count, dtype: int64

In [143]:
#Assigning frequencys for current awareness questions
data['1.2 current awareness'].replace({'very hard':'1',
                                       'hard':'2',
                                       'neutral':'3',
                                       'easy':'4',
                                       'very easy':'5'
                                       }, inplace=True)
data['1.1 current awareness'].replace({'very poor':'1',
                                       'poor':'2',
                                       'fair':'3',
                                       'good':'4',
                                       'very good':'5'
                                       }, inplace=True)
data['1.3 current awareness'].replace({'Always':'1',
                                       'Often':'2',
                                       'Sometimes':'3',
                                       'Rarely':'4',
                                       'Never':'5'
                                       }, inplace=True)
data['1.4 current awareness'].replace({'strongly disagree':'1',
                                       'Disagree':'2',
                                       'Neutral':'3',
                                       'Agree':'4',
                                       'Strongly agree':'5'
                                       }, inplace=True)
data

C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\3067770192.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['1.2 current awareness'].replace({'very hard':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\3067770192.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['1.1 current awareness'].replace({'very poor':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\3067770192.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['1.3 current awareness'].replace({'Always':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\3067770192.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['1.4 current awareness'].replace({'strongly disagree':'1',

,Name,Gender,Age,Employment Status,Education Qualification,District,Area of Residence,which type of Vehicle do you have?,Do you have an Electric Vehicle?,1.1 current awareness,...,4.5 cost consideration,5.1 consumer preference,5.2 consumer preference,5.3 consmer preference,5.4 consumer preference,5.5 consumer preference,6.1 evm consideration,6.2 evm consideration,6.3 evm consideration,6.4 evm consideration
0,Anish Glorisha,Female,18 - 27,Student,Post Graduate,Coimbatore,Urban,Petrol,No,3,...,High,familiar,Attracted,Very satisfied,Somewhat considered,Good,Similar to others,Neutral,Reduce,neutral
1,Hari,Male,18 - 27,Student,Post Graduate,coimbatore,Rural,Diesel,Yes,4,...,Low,Very unfamiliar,Highly not attracted,moderately satisfied,Somewhat considered,Average,Highly polluting,Useless,Didn't reduce,support
2,CHINNAPPANDI J,Male,18 - 27,Student,Post Graduate,coimbatore,Rural,Petrol,Yes,2,...,Very low,familiar,Not attracted,Very satisfied,Somewhat considered,Fair,Not polluting,Usefull,Definitely reduce,definitely support
3,P. Manikandan,Male,18 - 27,Student,Post Graduate,Viruthunagar,Urban,Diesel,Yes,1,...,Neutral,Somewhat familiar,Highly not attracted,moderately satisfied,Not considered,Fair,Similar to others,Usefull,Reduce,neutral
4,Divyasri,Female,18 - 27,Student,Post Graduate,Dharmapuri,Urban,Petrol,No,4,...,High,familiar,Not attracted,Slightly satisfied,Somewhat considered,Fair,slightly polluting,Neutral,Reduce,neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,Karuppaiya,Male,28 - 43,Employed,Diploma,Tiruppur,Urban,Petrol,No,4,...,Very low,familiar,Somewhat attracted,moderately satisfied,Somewhat considered,Poor,Highly not polluting,Very usefull,Definitely reduce,definitely support
197,Vishal,Male,18 - 27,Employed,Under Graduate,Tiruppur,Urban,Electric batteries,Yes,4,...,Low,Very familiar,Highly attracted,moderately satisfied,Considered,Poor,Highly not polluting,Very usefull,Definitely reduce,definitely support
198,Nivedha,Female,18 - 27,Employed,Post Graduate,Tiruppur,Urban,Petrol,No,4,...,Very low,familiar,Attracted,moderately satisfied,Somewhat considered,Poor,Highly not polluting,Very usefull,Definitely reduce,definitely support
199,Xavier,Male,18 - 27,Employed,Under Graduate,Tiruppur,Urban,Petrol,No,2,...,Very low,Very familiar,Attracted,moderately satisfied,Somewhat considered,Poor,Highly not polluting,Very usefull,Definitely reduce,definitely support
200,S.Gangaiarasan,Male,44 - 59,Employed,Post Graduate,Pudukkottai,Rural,Petrol,No,2,...,Very low,Unfamiliiar,Not attracted,Not at all satisfied,Not considered,Poor,Not polluting,Usefull,Reduce,neutral

In [144]:
#Assigning frequencies for user satisfaction questions

data['2.1 user satisfaction'].replace({'Very poor':'1',
                                       'Poor':'2',
                                       'Fair':'3',
                                       'Good':'4',
                                       'Very good':'5'}, inplace=True)
data['2.2 user satisfaction'].replace({'Strongly disagree':'1',
                                       'Disagree':'2',
                                       'Neither agree or disagree':'3',
                                       'Agree':'4',
                                       'Strongly agree':'5'}, inplace=True)

data['2.3 user satisfaction'].replace({'Very poor':'1',
                                       'Poor':'2',
                                       'Similar':'3',
                                       'Good':'4',
                                       'Very good':'5'}, inplace=True)
data['2.4 user satisfaction'].replace({'Very dissatisfied':'1',
                                       'Dissatisfied':'2',
                                       'Neither satisfied or dissatisfied':'3',
                                       'Satisfied':'4',
                                       'Very satisfied':'5'}, inplace=True)
data['2.5 user satisfaction'].replace({'Definitely never refill':'1',
                                       'Never refill':'2',
                                       'Neutral':'3',
                                       'Refill':'4',
                                       'Definitely refill':'5'}, inplace=True)
data['2.2 user satisfaction'].head()

C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1087210385.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['2.1 user satisfaction'].replace({'Very poor':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1087210385.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['2.2 user satisfaction'].replace({'Strongly disagree':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1087210385.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['2.3 user satisfaction'].replace({'Very poor':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1087210385.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['2.4 user satisfaction'].replace({'Very dissatisfied':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1087210385.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['2.5 user satisfaction'].replace({'Definitely never refill':'1',

0    2
1    3
2    5
3    2
4    4
Name: 2.2 user satisfaction, dtype: object

In [145]:
#Assigning frequencies for charging facilities questions

data['3.1 charging facilities'].replace({'Very poor':'1',
                                       'Poor':'2',
                                       'Acceptable':'3',
                                       'Good':'4',
                                       'Very good':'5'}, inplace=True)
data['3.2 charging facilities'].replace({'Very poor':'1',
                                       'Poor':'2',
                                       'Enough':'3',
                                       'Good':'4',
                                       'Very good':'5'}, inplace=True)
data['3.3 charging facilities'].replace({'Nothing':'1',
                                       'Some one':'2',
                                       'Somewhat':'3',
                                       'Enough':'4',
                                       'Lot':'5'}, inplace=True)
data['3.4 charging facilities'].replace({'Really bad':'1',
                                       'Bad':'2',
                                       'Neutral':'3',
                                       'Good':'4',
                                       'Really good':'5'}, inplace=True)

data['3.4 charging facilities'].head()

C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\2118599323.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['3.1 charging facilities'].replace({'Very poor':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\2118599323.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['3.2 charging facilities'].replace({'Very poor':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\2118599323.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['3.3 charging facilities'].replace({'Nothing':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\2118599323.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['3.4 charging facilities'].replace({'Really bad':'1',

0    4
1    2
2    1
3    1
4    4
Name: 3.4 charging facilities, dtype: object

In [146]:
#Assigning frequencies for cost consideration questions

data['4.1 cost consideration'].replace({'very expensive':'1',
                                       'Expensive':'2',
                                       'both are same':'3',
                                       'Cheap':'4',
                                       'Very cheap':'5'}, inplace=True)
data['4.2 cost consideration'].replace({'Very expensive':'1',
                                       'Expensive':'2',
                                       'Both are same':'3',
                                       'Cheap':'4',
                                       'Very cheap':'5'}, inplace=True)
data['4.3 cost consideration'].replace({'very expensive':'1',
                                       'Expensive':'2',
                                       'Both are same':'3',
                                       'Cheap':'4',
                                       'Very cheap':'5'}, inplace=True)
data['4.4 cost consideration'].replace({'Very high':'1',
                                       'High':'2',
                                       'similar to others':'3',
                                       'Low':'4',
                                       'Very low':'5'}, inplace=True)
data['4.5 cost consideration'].replace({'Very low':'1',
                                       'Low':'2',
                                       'Neutral':'3',
                                       'High':'4',
                                       'Very high':'5'}, inplace=True)

data['4.5 cost consideration'].head()

C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1065109942.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['4.1 cost consideration'].replace({'very expensive':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1065109942.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['4.2 cost consideration'].replace({'Very expensive':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1065109942.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['4.3 cost consideration'].replace({'very expensive':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1065109942.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['4.4 cost consideration'].replace({'Very high':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\1065109942.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['4.5 cost consideration'].replace({'Very low':'1',

0    4
1    2
2    1
3    3
4    4
Name: 4.5 cost consideration, dtype: object

In [147]:
#Assigning frequencies for consumer preference questions

data['5.1 consumer preference'].replace({'Very unfamiliar':'1',
                                       'Unfamiliiar':'2',
                                       'Somewhat familiar':'3',
                                       'familiar':'4',
                                       'Very familiar':'5'}, inplace=True)
data['5.2 consumer preference'].replace({'Highly not attracted':'1',
                                       'Not attracted':'2',
                                       'Somewhat attracted':'3',
                                       'Attracted':'4',
                                       'Highly attracted':'5'}, inplace=True)
data['5.3 consmer preference'].replace({'Not at all satisfied':'1',
                                       'Slightly satisfied':'2',
                                       'moderately satisfied':'3',
                                       'Very satisfied':'4',
                                       'Extremely satisfied':'5'}, inplace=True)
data['5.4 consumer preference'].replace({'Highly not considered':'1',
                                       'Not considered':'2',
                                       'Somewhat considered':'3',
                                       'Considered':'4',
                                       'Highly considered':'5'}, inplace=True)
data['5.5 consumer preference'].replace({'Poor':'1',
                                       'Fair':'2',
                                       'Average':'3',
                                       'Good':'4',
                                       'Excellent':'5'}, inplace=True)

data['5.5 consumer preference'].head()

C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\4078465753.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['5.1 consumer preference'].replace({'Very unfamiliar':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\4078465753.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['5.2 consumer preference'].replace({'Highly not attracted':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\4078465753.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['5.3 consmer preference'].replace({'Not at all satisfied':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\4078465753.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['5.4 consumer preference'].replace({'Highly not considered':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\4078465753.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['5.5 consumer preference'].replace({'Poor':'1',

0    4
1    3
2    2
3    2
4    2
Name: 5.5 consumer preference, dtype: object

In [148]:
#Assigning frequencies for evm consideration questions

data['6.1 evm consideration'].replace({'Highly polluting':'1',
                                       'slightly polluting':'2',
                                       'Similar to others':'3',
                                       'Not polluting':'4',
                                       'Highly not polluting':'5'}, inplace=True)
data['6.2 evm consideration'].replace({'Very useless':'1',
                                       'Useless':'2',
                                       'Neutral':'3',
                                       'Usefull':'4',
                                       'Very usefull':'5'}, inplace=True)
data['6.3 evm consideration'].replace({"Definitely didn't reduce":'1',
                                       "Didn't reduce":'2',
                                       'Similar to others':'3',
                                       'Reduce':'4',
                                       'Definitely reduce':'5'}, inplace=True)
data['6.4 evm consideration'].replace({'definitely never support':'1',
                                       'never support':'2',
                                       'neutral':'3',
                                       'support':'4',
                                       'definitely support':'5'}, inplace=True)

data['6.4 evm consideration'].head()

C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\2252568429.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['6.1 evm consideration'].replace({'Highly polluting':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\2252568429.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['6.2 evm consideration'].replace({'Very useless':'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\2252568429.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['6.3 evm consideration'].replace({"Definitely didn't reduce":'1',
C:\Users\ANAND\AppData\Local\Temp\ipykernel_5596\2252568429.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['6.4 evm consideration'].replace({'definitely never support':'1',

0    3
1    4
2    5
3    3
4    3
Name: 6.4 evm consideration, dtype: object

In [149]:
data.head()

,Name,Gender,Age,Employment Status,Education Qualification,District,Area of Residence,which type of Vehicle do you have?,Do you have an Electric Vehicle?,1.1 current awareness,...,4.5 cost consideration,5.1 consumer preference,5.2 consumer preference,5.3 consmer preference,5.4 consumer preference,5.5 consumer preference,6.1 evm consideration,6.2 evm consideration,6.3 evm consideration,6.4 evm consideration
0,Anish Glorisha,Female,18 - 27,Student,Post Graduate,Coimbatore,Urban,Petrol,No,3,...,4,4,4,4,3,4,3,3,4,3
1,Hari,Male,18 - 27,Student,Post Graduate,coimbatore,Rural,Diesel,Yes,4,...,2,1,1,3,3,3,1,2,2,4
2,CHINNAPPANDI J,Male,18 - 27,Student,Post Graduate,coimbatore,Rural,Petrol,Yes,2,...,1,4,2,4,3,2,4,4,5,5
3,P. Manikandan,Male,18 - 27,Student,Post Graduate,Viruthunagar,Urban,Diesel,Yes,1,...,3,3,1,3,2,2,3,4,4,3
4,Divyasri,Female,18 - 27,Student,Post Graduate,Dharmapuri,Urban,Petrol,No,4,...,4,4,2,2,3,2,2,3,4,3

In [150]:
#Change the columns name
data.rename(columns={'which type of Vehicle do you have?':"type of vehicle",
                     'Do you have an Electric Vehicle?':'EV'},
                     inplace=True)
data.columns

Index(['Name', 'Gender', 'Age', 'Employment Status',
       'Education Qualification ', 'District', 'Area of Residence',
       'type of vehicle', 'EV', '1.1 current awareness',
       '1.2 current awareness', '1.3 current awareness',
       '1.4 current awareness', '2.1 user satisfaction',
       '2.2 user satisfaction', '2.3 user satisfaction',
       '2.4 user satisfaction', '2.5 user satisfaction',
       '3.1 charging facilities', '3.2 charging facilities',
       '3.3 charging facilities', '3.4 charging facilities',
       '4.1 cost consideration', '4.2 cost consideration',
       '4.3 cost consideration', '4.4 cost consideration',
       '4.5 cost consideration', '5.1 consumer preference',
       '5.2 consumer preference', '5.3 consmer preference',
       '5.4 consumer preference', '5.5 consumer preference',
       '6.1 evm consideration', '6.2 evm consideration',
       '6.3 evm consideration', '6.4 evm consideration'],
      dtype='object')

In [152]:
#Save the customized data
data_set=data
data_set.to_csv("d:/pg project responses/new respo customized.csv")