In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('d:\pg project responses\cust_res.csv')
df

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\ANAND\AppData\Local\Temp\ipykernel_648\852158826.py:1: SyntaxWarning: invalid escape sequence '\p'
  df=pd.read_csv('d:\pg project responses\cust_res.csv')

,Unnamed: 0,Name,Gender,Age,Employment Status,Education Qualification,District,Area of Residence,type of vehicle,EV,...,4.5 cost consideration,5.1 consumer preference,5.2 consumer preference,5.3 consmer preference,5.4 consumer preference,5.5 consumer preference,6.1 evm consideration,6.2 evm consideration,6.3 evm consideration,6.4 evm consideration
0,0,Anish Glorisha,Female,18 - 27,Student,Post Graduate,Coimbatore,Urban,Petrol,No,...,4,4,4,4,3,4,3,3,4,3
1,1,Hari,Male,18 - 27,Student,Post Graduate,coimbatore,Rural,Diesel,Yes,...,2,1,1,3,3,3,1,2,2,4
2,2,CHINNAPPANDI J,Male,18 - 27,Student,Post Graduate,coimbatore,Rural,Petrol,Yes,...,1,4,2,4,3,2,4,4,5,5
3,3,P. Manikandan,Male,18 - 27,Student,Post Graduate,Viruthunagar,Urban,Diesel,Yes,...,3,3,1,3,2,2,3,4,4,3
4,4,Divyasri,Female,18 - 27,Student,Post Graduate,Dharmapuri,Urban,Petrol,No,...,4,4,2,2,3,2,2,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,196,Karuppaiya,Male,28 - 43,Employed,Diploma,Tiruppur,Urban,Petrol,No,...,1,4,3,3,3,1,5,5,5,5
197,197,Vishal,Male,18 - 27,Employed,Under Graduate,Tiruppur,Urban,Electric batteries,Yes,...,2,5,5,3,4,1,5,5,5,5
198,198,Nivedha,Female,18 - 27,Employed,Post Graduate,Tiruppur,Urban,Petrol,No,...,1,4,4,3,3,1,5,5,5,5
199,199,Xavier,Male,18 - 27,Employed,Under Graduate,Tiruppur,Urban,Petrol,No,...,1,5,4,3,3,1,5,5,5,5
200,200,S.Gangaiarasan,Male,44 - 59,Employed,Post Graduate,Pudukkottai,Rural,Petrol,No,...,1,2,2,1,2,1,4,4,4,3

In [1]:
pip install scikitlearn

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement scikitlearn (from versions: none)
ERROR: No matching distribution found for scikitlearn

Note: you may need to restart the kernel to use updated packages.

ERROR: unknown command "packages"